### ISSUE TITLE
Missing ./credentials.js

### ISSUE THREAD

**Issue by AbrahamGames** [AnigamiYT/Anigami#3]
Don't have an example or file for the ./credentials.js ):

**Comment by phuongbag** [comment]
here is the template:

`module.exports = {
    token: <token>,
    database: {
        host: "<HOST>",
        user: "<USER>",
        password: "<PW>",
        database: "<DATABASE>"
    },
}`

you'll also need to setup an sql table named USERDATA in database with columns DISCORDID INT, MORA INT, RESIN INT, and DATA BLOB

**Comment by AbrahamGames** [comment]
Right, in HOST how I setup?

**Comment by phuongbag** [comment]
check the pull requests maybe

**Comment by AnigamiYT** [comment]
I'll push a template later for everyone's use
